version: "3.7"

services:

  db:
     image: mysql:8
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root_password_123
       MYSQL_DATABASE: minyay
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: db_password_123
     command: --init-file /data/application/init.sql
     ports:
       - '3306:3306'
     expose:
       - '3306' 
     volumes:
       - ~/buddy/data/init.sql:/data/application/init.sql 

  php:
    image: php:7.2-fpm
    volumes:
      - ~/buddy/src:/var/www/myapp
      - ~/buddy/docker/php.ini:/usr/local/etc/php/php.ini
     
  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ~/buddy/src:/var/www/myapp
      - ~/buddy/docker/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - db

  composer:
    image: composer:2.0
    command: ["composer", "update"]
    working_dir: /var/www/myapp/src/server/composer
    volumes:
      - ~/buddy/src/server/composer:/var/www/myapp/src/server/composer
    depends_on:
      - web
